"""initial schema

Revision ID: 1a6005f244e2
Revises: 
Create Date: 2026-03-24 18:07:37.109100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6005f244e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('place_parking_id_num_place_key'), type_='unique')
        batch_op.create_unique_constraint('uq_place_parking_num_place', ['parking_id', 'num_place'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_constraint('uq_place_parking_num_place', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('place_parking_id_num_place_key'), ['parking_id', 'num_place'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
